package com.libratech.mia.models;

import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BandedProduct.java
//  @ Date : 1/12/2014
//  @ Author : 
//
//

public class BandedProduct {
	private float totalPrice;
	private ArrayList<Product> products;
	private String bandedID;

	public BandedProduct(String id, float totalPrice,
			ArrayList<Product> products) {
		bandedID = id;
		this.totalPrice = totalPrice;
		this.products = products;
	}

	public float getTotalPrice() {
		return totalPrice;
	}

	public void setTotalPrice(float totalPrice) {
		this.totalPrice = totalPrice;
	}

	public String getBandedID() {
		return bandedID;
	}

	public void setBandedID(String bandedID) {
		this.bandedID = bandedID;
	}

	public BandedProduct() {
		this.totalPrice = (float) 0.00;
		this.products = new ArrayList<Product>();
	}

	public float gettotalPrice() {
		return totalPrice;
	}

	public void settotalPrice(float totalPrice) {
		this.totalPrice = totalPrice;
	}

	public ArrayList<Product> getProducts() {
		return products;
	}

	public void setProducts(ArrayList<Product> products) {
		this.products = products;
	}

}
