package com.libratech.mia.models;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DiscountedProduct.java
//  @ Date : 1/12/2014
//  @ Author : 
//
//

public class DiscountedProduct {
	private String discValue;
	private String discType;
	private String upc;
	private String name;
	private String brand;
	private String weight;
	private String uom;
	private String photo;

	public DiscountedProduct(String upc, String name, String brand,
			String weight, String uom, String photo, String value, String type) {
		this.discValue = value;
		this.discType = type;
		this.upc = upc;
		this.name = name;
		this.brand = brand;
		this.weight = weight;
		this.uom = uom;
		this.photo = photo;
	}

	public String getUpc() {
		return upc;
	}

	public void setUpc(String upc) {
		this.upc = upc;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getWeight() {
		return weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

	public String getUom() {
		return uom;
	}

	public void setUom(String uom) {
		this.uom = uom;
	}

	public String getPhoto() {
		return photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public String getDiscValue() {
		return discValue;
	}

	public void setDiscValue(String discValue) {
		this.discValue = discValue;
	}

	public String getDiscType() {
		return discType;
	}

	public void setDiscType(String discType) {
		this.discType = discType;
	}

	public String getBrand() {
		return brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

}
