package com.libratech.mia.models;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DiscountedProduct.java
//  @ Date : 1/12/2014
//  @ Author : 
//
//




public class DiscountedProduct extends Product 
{
	private String discValue;

	public DiscountedProduct(String upcCode, String weight, String productName,
			String description, String brand, String category, String uom,
			float price, String gct, String photo, String discValue) 
	{
		super(upcCode, weight, productName, description, brand, category, uom,
				price, gct, photo);
		this.discValue = discValue;
	}

	public String getDiscValue() {
		return discValue;
	}

	public void setDiscValue(String discValue) {
		this.discValue = discValue;
	}
		
}
