package com.libratech.mia.models;
import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : InStoreSampleList.java
//  @ Date : 1/12/2014
//  @ Author : 
//
//




public class InStoreSampleList 
{
	private ArrayList <InStoreSample> inStoreSamples;

	public InStoreSampleList(ArrayList<InStoreSample> inStoreSamples) 
	{
		this.inStoreSamples = inStoreSamples;
	}

	public ArrayList<InStoreSample> getInStoreSamples() {
		return inStoreSamples;
	}

	public void setInStoreSamples(ArrayList<InStoreSample> inStoreSamples) {
		this.inStoreSamples = inStoreSamples;
	}
	
	
}
