package com.libratech.mia.models;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Merchandiser.java
//  @ Date : 1/12/2014
//  @ Author : 
//
//




public class Merchandiser extends Employee 
{

	public Merchandiser(String empID, String firstName, String lastName,
			String dob, String streetNo, String streetName, String city,
			String phoneNumber) 
	{
		super(empID, firstName, lastName, dob, streetNo, streetName, city, phoneNumber);
		// TODO Auto-generated constructor stub
	}
	
}
