package com.libratech.mia.models;

import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ProductList.java
//  @ Date : 1/12/2014
//  @ Author : 
//
//

public class Products {
	private ArrayList<Scanned> sP = new ArrayList<Scanned>();
	private ArrayList<Scanned> uP = new ArrayList<Scanned>();

	public Products() {

	}

	public ArrayList<Scanned> getScanned() {
		return sP;
	}

	public ArrayList<Scanned> getUnscanned() {
		return uP;
	}
}