package com.libratech.mia.models;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ScanRequest.java
//  @ Date : 1/12/2014
//  @ Author : 
//
//




public class ScanRequest 
{
	private String requestNo;
	private Product product;
	private Store store;
	
	public ScanRequest(String requestNo, Product product, Store store) 
	{
		this.requestNo = requestNo;
		this.product = product;
		this.store = store;
	}

	public String getRequestNo() {
		return requestNo;
	}

	public void setRequestNo(String requestNo) {
		this.requestNo = requestNo;
	}

	public Product getProduct() {
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Store getStore() {
		return store;
	}

	public void setStore(Store store) {
		this.store = store;
	}
	
	
	
	
}
