package com.libratech.mia.models;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Store.java
//  @ Date : 1/12/2014
//  @ Author : 
//
//




public class Store 
{
	private String storeID;
	private String companyName;
	private String streetNo;
	private String streetName;
	private String city;
	
	public Store(String storeID, String companyName, String streetNo,
			String streetName, String city) 
	{		
		this.storeID = storeID;
		this.companyName = companyName;
		this.streetNo = streetNo;
		this.streetName = streetName;
		this.city = city;
	}

	public String getStoreID() {
		return storeID;
	}

	public void setStoreID(String storeID) {
		this.storeID = storeID;
	}

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getStreetNo() {
		return streetNo;
	}

	public void setStreetNo(String streetNo) {
		this.streetNo = streetNo;
	}

	public String getStreetName() {
		return streetName;
	}

	public void setStreetName(String streetName) {
		this.streetName = streetName;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}
	
	
}
