package com.libratech.mia.models;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Store.java
//  @ Date : 1/12/2014
//  @ Author : 
//
//

public class Store {
	private String storeID;
	private String companyName;
	private String addr;
	private String city;

	public Store(String storeID, String companyName, String addr, String city) {
		this.storeID = storeID;
		this.companyName = companyName;
		this.addr = addr;
		this.city = city;
	}

	public Store(String storeID, String companyName) {
		this.storeID = storeID;
		this.companyName = companyName;
	}

	public Store() {
		this.storeID = "";
		this.companyName = "";
		this.addr = "";
		this.city = "";
	}

	public String getStoreID() {
		return storeID;
	}

	public void setStoreID(String storeID) {
		this.storeID = storeID;
	}

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getAddress() {
		return addr;
	}

	public void setAddress(String addr) {
		this.addr = addr;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

}
