package com.libratech.mia.models;
import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StoreList.java
//  @ Date : 1/12/2014
//  @ Author : 
//
//




public class StoreList 
{
	private ArrayList <Store> stores;

	public StoreList(ArrayList<Store> stores) 
	{
		this.stores = stores;
	}

	public ArrayList<Store> getStores() {
		return stores;
	}

	public void setStores(ArrayList<Store> stores) {
		this.stores = stores;
	}
	
	
}
