package com.libratech.mia.models;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Unscanned.java
//  @ Date : 1/12/2014
//  @ Author : 
//
//




public class Unscanned extends Product 
{

	public Unscanned(int upcCode, int weight, String productName,
			String description, String brand, String category, String uom,
			float price, String gct, String photo)
	{
		super(upcCode, weight, productName, description, brand, category, uom, price,
				gct, photo);
		// TODO Auto-generated constructor stub
	}
	
}
