import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BandedProductList.java
//  @ Date : 1/12/2014
//  @ Author : 
//
//




public class BandedProductList 
{
	private ArrayList <BandedProduct>bandedProducts;

	public BandedProductList(ArrayList<BandedProduct> bandedProducts) 
	{		
		this.bandedProducts = bandedProducts;
	}

	public ArrayList<BandedProduct> getBandedProducts() {
		return bandedProducts;
	}

	public void setBandedProducts(ArrayList<BandedProduct> bandedProducts) {
		this.bandedProducts = bandedProducts;
	}
	
	
}
