import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DiscountList.java
//  @ Date : 1/12/2014
//  @ Author : 
//
//




public class DiscountList 
{
	private ArrayList <DiscountedProduct> discountedProducts;

	public DiscountList(ArrayList<DiscountedProduct> discountedProducts)
	{
		this.discountedProducts = discountedProducts;
	}

	public ArrayList<DiscountedProduct> getDiscountedProducts() {
		return discountedProducts;
	}

	public void setDiscountedProducts(
			ArrayList<DiscountedProduct> discountedProducts) {
		this.discountedProducts = discountedProducts;
	}
	
	
}
