import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ProductList.java
//  @ Date : 1/12/2014
//  @ Author : 
//
//


public class ProductList 
{
	private ArrayList <Product> products;

	public ProductList(ArrayList<Product> products) 
	{
		this.products = products;
	}

	public ArrayList<Product> getProducts() {
		return products;
	}

	public void setProducts(ArrayList<Product> products) {
		this.products = products;
	}
	
	
}
