//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Product.java
//  @ Date : 1/12/2014
//  @ Author : 
//
//




public class Product 
{
	private int upcCode;
	private int weight;
	private String productName;
	private String description;
	private String brand;
	private String category;
	private String uom;
	private float price;
	private String gct;
	private String photo;
	
	public Product(int upcCode, int weight, String productName,
			String description, String brand, String category, String uom,
			float price, String gct, String photo) 
	{		
		this.upcCode = upcCode;
		this.weight = weight;
		this.productName = productName;
		this.description = description;
		this.brand = brand;
		this.category = category;
		this.uom = uom;
		this.price = price;
		this.gct = gct;
		this.photo = photo;
	}

	public int getUpcCode() {
		return upcCode;
	}

	public void setUpcCode(int upcCode) {
		this.upcCode = upcCode;
	}

	public int getWeight() {
		return weight;
	}

	public void setWeight(int weight) {
		this.weight = weight;
	}

	public String getProductName() {
		return productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getBrand() {
		return brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getUom() {
		return uom;
	}

	public void setUom(String uom) {
		this.uom = uom;
	}

	public float getPrice() {
		return price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public String getGct() {
		return gct;
	}

	public void setGct(String gct) {
		this.gct = gct;
	}

	public String getPhoto() {
		return photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}
	
}
