import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ScanRequestList.java
//  @ Date : 1/12/2014
//  @ Author : 
//
//




public class ScanRequestList 
{
	private ArrayList <ScanRequest> scanRequests;

	public ScanRequestList(ArrayList<ScanRequest> scanRequests)
	{
		this.scanRequests = scanRequests;
	}

	public ArrayList<ScanRequest> getScanRequests() {
		return scanRequests;
	}

	public void setScanRequests(ArrayList<ScanRequest> scanRequests) {
		this.scanRequests = scanRequests;
	}
	
	
}
